---
title: "ODE model"
author: "Emmerson Wilson"
date: "2024-06-19"
output: html_document
---

```{r}
pacman::p_load(
  tidyverse,
  deSolve)

setwd("/Users/emmersonEmmerson/Documents/Master's/C_forecasting_NL/code_for_stats/for odes")
```

# model structure
```{r}
lv <- function(times, state, parms) {
  with(as.list(c(state, parms)), {
# moose
    Consumption    <- ((a * Pyoung)/(1 + a * h * Pyoung)) * Moose
    Death <- lM * (Moose^2)
    
    # palatable 
    GrowthPy <- rPy * Pyoung * (1 - (Pyoung + Pmature + alphaUPy * Unpal)/kPy)
    NewSeed <- s * Pmature
    DeathPy <- lPy * Pyoung
    GrowthPm <- rPm * Pmature * (1 - (Pyoung + Pmature + alphaUPm * Unpal)/kPm) # rate of growth decreases by at least a third by the time a tree reaches 10 yrs (or approximately 3 m)
    #Ageing <- if(times <= 1/g) 0 else g * Pyoung  
    Ageing <- (g^(3*(Consumption)/(Pyoung+0.01))) * Pyoung #need to add small amount to Pyoung in denominator
    DeathPm <- lPm * Pmature
    
    # unpalatable
    GrowthU <- rU * Unpal * (1 - (alphaPyU * Pyoung + alphaPmU * Pmature + Unpal)/kU)
    DeathU <- lU * Unpal

    # odes
    dMoose  <- Consumption*e - Death 
    dPyoung <- GrowthPy + NewSeed - Consumption - Ageing - DeathPy
    dPmature <- GrowthPm + Ageing - DeathPm
    dUnpal <- GrowthU - DeathU
    

    list(c(dMoose, dPyoung, dPmature, dUnpal))
  })
}
```

## parameters
```{r}
parms  <- c(a = 0.9985, #from Lunberg and Danelle 1990
            h = 0.0223, # 1/max intake in Mg per Mg moose per year (similar to handling time of Lunberg and Denelle)
            e = 0.02, #0.02 leads to max reasonable stable moose pop, prefer 0.01
            lM = 0.3234,
            rPy = 0.2,
            rPm = 0.14,
            s = 0.011,
            alphaUPy = 0.001,
            alphaUPm = 0.0001, # should have almost no effect
            kPy = 1000,
            kPm = 68000, # includes only live veg
            g = 0.133, # 1/time to reach 3m
            lPm = 0.01,
            lPy = 0.2,
            rU = 0.9,
            alphaPyU = 0.002, # less than alphaPmU, but more than alphaUpy
            alphaPmU = 0.006, # level so that kPm*alpha < kU, so that some upalatable species do persist, as seen in field
            kU = 900,
            lU = 0.4)
```

## starting conditions
```{r}
time_vec1 <- seq(from = 1, to = 1500, length.out = 1500)

y_0 <- c(Moose = 0.2068966, Pyoung = 172.41379, Pmature = 0, Unpal = 100)
```

## extinction
```{r}
eps <- 1e-2
## event triggered if state variable <= eps
eventfun <- function(times, y, parms) {
  y[which(y<eps | y<0)] <- 0 
  return(y)
}
```

## run model
```{r}
#with extinction
# out1 <- ode(y = state, times = time_vec1, func = lv, parms = parms, method = "lsoda", rootfun = rootfun, events = list(func = eventfun, root = TRUE))

# with Alex's code
# Run ode - supply the whole time vector as event times
out2 <- ode(y = y_0, times = time_vec1, func = lv, parms = parms, events=list(func = eventfun, time = time_vec1))

```

## plot
```{r}
long_out2 <- as.data.frame(out2) %>% 
  pivot_longer(cols = c(2:5))

ggplot(long_out2, aes(x = time, y = value)) +
  geom_line() +
  facet_wrap(~name, scales = "free") +
  theme_bw() 

out2_tol <- ode(y = y_0, times = time_vec1, func = lv, parms = parms, events=list(func = eventfun, time = time_vec1, atol = 1e-4, rtol = 1e-4))

ggplot(subset(long_out2, time >= 207 & name == "Unpal"), aes(x = time, y = value)) +
  geom_line() +
  facet_wrap(~name, scales = "free") +
  theme_bw() + 
  scale_y_continuous(labels = scales::number_format(accuracy = 0.00001), limits = c(121.3138507038, 121.3138507043))

as.numeric(sprintf("%.10f",max(subset(long_out2, time >= 400 & name == "Moose")$value))) - as.numeric(sprintf("%.10f",min(subset(long_out2, time >= 400 & name == "Moose")$value)))
```


```{r}
#cycles happen in same way if start model at value found within cycles

# psuedo phase portrait
ggplot(subset(out2, time >= 1000), aes(x = Moose, y = Pmature)) +
  geom_line() +
  theme_bw() + 
  scale_y_continuous(labels = scales::number_format(accuracy = 0.000000001))

# zoom in on cycle
ggplot(subset(long_out2, time >= 997 & time <=1142), aes(x = time, y = value)) + #cycles seem to be 105 years 
  geom_line() +
  facet_wrap(~name, scales = "free", ncol = 1) +
  theme_bw() + 
  scale_y_continuous(labels = scales::number_format(accuracy = 0.00000000001))

#freq
#after cycles start
ggplot(subset(long_out2, time >= 997 & name == "Unpal"), aes(value)) +
 geom_density() +
  theme_bw()+ 
  scale_x_continuous(labels = scales::number_format(accuracy = 0.00000000001))

#during one cycle
ggplot(subset(long_out2, time >= 997 & time <=1142 & name == "Unpal"), aes(value)) +
 geom_density() +
  theme_bw()+ 
  scale_x_continuous(labels = scales::number_format(accuracy = 0.00000000001))

# after reaches "regime" visually
ggplot(subset(long_out2, time >= 400 & name == "Unpal"), aes(value)) +
 geom_density() +
  theme_bw()+ 
  scale_x_continuous(labels = scales::number_format(accuracy = 0.00000000001))

#between 0 and end of first cycle
ggplot(subset(long_out2, time >= 00 & time <= 1142 & name == "Unpal"), aes(value)) + 
 geom_density() +
  theme_bw()+ 
  scale_x_continuous(labels = scales::number_format(accuracy = 0.00000000001))

# zoom in 
ggplot(subset(long_out2, time >= 00 & time <= 1142 & name == "Unpal"), aes(value)) + #between 0 and end of first cycle
 geom_density() +
  theme_bw()+ 
  scale_x_continuous(labels = scales::number_format(accuracy = 0.00000000001), limits = c(121.4, 500))
```

# sensitivity

## ODEsensitivity
to help choose which parameters to vary across simulations
```{r}
library(ODEsensitivity)

# put lv un function with event

lv_event <- function(Time, State, Pars) {
  with(as.list(c(State, Pars)), {
  
  Consumption    <- ((a * Pyoung)/(1 + a * h * Pyoung)) * e * Moose
    Death <- lM * (Moose^2)
    
    # palatable 
    GrowthPy <- rP * (Pyoung) * (1 - (Pyoung + Pmature + alphaUPy * Unpal)/kPy)
    NewSeed <- s * Pmature
    GrowthPm <- rP * (Pmature) * (1 - (Pyoung + Pmature + alphaUPm * Unpal)/kPm)
    Ageing <- if(Time <= 7.5) 0 else g * Pyoung  
    DeathPm <- lPm * Pmature
    
    # unpalatable
    GrowthU <- rU * Unpal * (1 - (alphaPyU * Pyoung + alphaPmU * Pmature + Unpal)/kU)
    DeathU <- lU * Unpal

    # odes
    dMoose  <- Consumption - Death 
    dPyoung <- GrowthPy + NewSeed - Consumption/e - Ageing
    dPmature <- GrowthPm + Ageing - DeathPm
    dUnpal <- GrowthU - DeathU
    
  dMoose[which(dMoose<eps)] <- 0 
  dPyoung[which(dPyoung<eps)] <- 0 
  dPmature[which(dPmature<eps)] <- 0 
  dUnpal[which(dUnpal<eps)] <- 0 
  
  list(c(dMoose, dPyoung, dPmature, dUnpal))
  })
}

# set bounds of parameters
LVparms <-  c("a", "h", "e", "lM", "rP", "s", "alphaUPy", "alphaUPm", "kPy", "kPm", "g", "lPm", "rU", "alphaPyU", "alphaPmU", "kU", "lU")
LVlow <- c(0.8, 0.01, 0.009, 0.196, 0.1, 0.009, 0.0005, 0.0001, 1000, 50000, 0.1, 0.005, 0.2, 0.0005, 0.0005, 100, 0.005)
LVhigh <- c(1.1, 0.03, 0.05, 0.36, 0.3, 0.02, 0.01, 0.001, 10000,300000,  0.333, 0.02, 0.5, 0.01, 0.01, 5000, 0.1)


LVres_sobol <- ODEsobol(mod = lv_event,
  pars = LVparms, n = 50, rfuncs = "runif",
  state_init = y_0,
  times = time_vec1, binf = LVlow, bsup = LVhigh,
  sobol_method = "Martinez",
  ode_method = "lsoda")


moose_param <-  c("a", "h", "e", "lM")
pal_param <- c("rPy", "s", "alphaUPy", "alphaUPm", "kPy", "kPm", "rPm", "g", "lPm")
unpal_param <- c("rU", "alphaPyU", "alphaPmU", "kU", "lU")

plot(LVres_sobolm, pars_plot = moose_param, state_plot = "Moose") 
plot(LVres_sobolm, pars_plot = pal_param, state_plot = "Moose") 
plot(LVres_sobolm, pars_plot = unpal_param, state_plot = "Moose") 

plot(LVres_sobolm, pars_plot = moose_param, state_plot = "Pyoung") 
plot(LVres_sobolm, pars_plot = pal_param, state_plot = "Pyoung") 
plot(LVres_sobolm, pars_plot = unpal_param, state_plot = "Pyoung") 

plot(LVres_sobolm, pars_plot = moose_param, state_plot = "Pmature") 
plot(LVres_sobolm, pars_plot = pal_param, state_plot = "Pmature") 
plot(LVres_sobolm, pars_plot = unpal_param, state_plot = "Pmature")

plot(LVres_sobolm, pars_plot = moose_param, state_plot = "Unpal") 
plot(LVres_sobolm, pars_plot = pal_param, state_plot = "Unpal") 
plot(LVres_sobolm, pars_plot = unpal_param, state_plot = "Unpal")

# this depends highly on starting conditions

# so run this multiple times with many starting conditions? low medium high?
```

## FME
```{r}
library(FME)


solvelv <- function(param) {
  state <- y_0
  tout  <- seq(from = 1, to = 200, length.out = 200)
  ## ode solves the model by integration ...
  return(as.data.frame(ode(y = state, times = tout, func = lv,
    parms = param, method = "lsoda",
           events = list(func = eventfun, time = tout))))
}



s_out <- solvelv(parms)

## the local sensitivity to parameters 

SensF <- sensFun(func = solvelv, parms = parms,
           sensvar = c("Pmature"))
Sens2F <- summary(SensF)
Sens2Fabs <- abs(Sens2F)

## Plot all variables; plot mean +- sd, min max
plot(Sens2F)
plot(Sens2Fabs)
var(SensF)

# global sensitivity over time to parameters space over time

LVlow <-  c(0.5, 0.005, 0.005, 0.196, 0.05, 0.005, 0.0005, 0.00005, 200, 50000,0.05,0.1,0.005,0.1,0.0005,0.0005,100,0.005)
LVhigh <-  c(1.5, 0.04, 0.05, 0.36, 0.4, 0.03, 0.01, 0.001, 10000,300000, 0.4,0.333,0.02,0.5,0.01,0.01,5000,0.1)

param_space <- data.frame(min = LVlow, max = LVhigh)
rownames(param_space)<- names(parms)

Sens2_t <- sensRange(func = solvelv, parms = parms, dist = "latin", parRange = param_space, num = 200,  sensvar = "Pmature")

Sens2_tsum <- summary(Sens2_t)

## Plot all variables; plot mean +- sd, min max
plot(Sens2_t, xlab = "time, year", ylab = "Mg",
main = "Sensitivity to params", mfrow = NULL)

Sens2_t_p <- Sens2_t %>% select(!c("a", "h", "e", "lM", "rU", "alphaPyU", "alphaPmU", "kU", "lU"))

plot(Sens2_t_p, xlab = "time, year", ylab = "Mg",
main = "Sensitivity to params", mfrow = NULL)


plot(Sens2_tsum, xlab = "time, year", ylab = "Mg",
main = "Sensitivity to params", mfrow = NULL)

# global sensitivity to parameter space 

SF <- function (param) {
out <- solvelv(param)
return(out[nrow(out), 2:5])
}

SF(param)

Sens2_ <- sensRange(func = SF,parms = parms, dist = "latin", parRange = param_space, num = 200) 
Sens2_sum <- summary(Sens2_)
plot(Sens2_, which = c("Moose", "Pyoung", "Pmature", "Unpal"))


CRL <- modCRL(func = SF, parRange = param_space, dist = "latin")
summary(CRL)
plot(CRL)
```


# FME over starting conditions
```{r}
# local sensitivity of final condition of Pm, for all range of initial conditions
n_i <- 20

M_init <- seq(0, 6, length.out = n_i)
Py_init <- seq(0, 1500, length.out = n_i)
Pm_init <- rep(0, n_i)
U_init <- rep(100, n_i)

init_seq <- data.frame(Moose=rep(M_init, each = n_i), Pyoung = rep(Py_init, n_i), Pmature = rep(Pm_init,n_i), Unpal = rep(U_init,n_i))

y_0d <- split(as.matrix(init_seq), row(init_seq)) %>% 
  lapply(setNames, nm = c("Moose", "Pyoung", "Pmature", "Unpal"))

solvelv2 <- list()


for(i in 1:length(y_0d)) {
 solvelv2[[i]] <- function(param) {
   state <- y_0d[[i]]
   tout <- seq(from = 1, to = 200, length.out = 200)
  ## ode solves the model by integration ...
  return(as.data.frame(ode(y = state, times = tout, func = lv,
    parms = param, method = "lsoda",
           events = list(func = eventfun, time = tout))))
 }
}


SensF_param <- lapply(solvelv2, sensFun, parms = parms, sensvar = c("Pmature")) # think parscale scales to 1, else the immense size of kPm rellative to everything else makes it dominate

SensF_param_abs2 <- list()

SensF_param_abs <- lapply(SensF_param, summary)

SensF_param_abs_mean <- Reduce("+", SensF_param_abs)/length(SensF_param_abs)


SensF_param_abs_mean_grp <- SensF_param_abs_mean %>% 
  mutate(parameter = rownames(SensF_param_abs_mean)) %>% 
  group_by(parameter)

ggplot(SensF_param_abs_mean_grp, aes(x = parameter, y = Mean)) +
  geom_point()
ggplot(SensF_param_abs_mean_grp, aes(x = parameter, y = L1)) +
  geom_point()
ggplot(SensF_param_abs_mean_grp, aes(x = parameter, y = L2)) +
  geom_point()
ggplot(SensF_param_abs_mean_grp, aes(x = parameter, y = Min)) +
  geom_point()
ggplot(SensF_param_abs_mean_grp, aes(x = parameter, y = Max)) +
  geom_point()

# seems parameters that effect the rate of consumption by moose, and the net growth of mature browsed plants effect the end condition the most
```

# rootsolve
```{r}
library(rootSolve)
# cant pass event function

# try explicitly putting event in funciton, cnat get to work
state2 <- y_0
lv_event3 <- function(times, state, parms) {
  with(as.list(c(state, parms)), {
  ifelse(Moose < eps,
    # moose
    
    # palatable 
    GrowthPy <- rP * (Pyoung) * (1 - (Pyoung + Pmature + alphaUPy * Unpal)/kPy)
    NewSeed <- s * Pmature
    GrowthPm <- rP * (Pmature) * (1 - (Pyoung + Pmature + alphaUPm * Unpal)/kPm)
    Ageing <- if(times <= 1/g) 0 else g * Pyoung  
    DeathPm <- lPm * Pmature
    
    # unpalatable
    GrowthU <- rU * Unpal * (1 - (alphaPyU * Pyoung + alphaPmU * Pmature + Unpal)/kU)
    DeathU <- lU * Unpal

    # odes
    dMoose  <- - Moose 
    dPyoung <- GrowthPy + NewSeed - Consumption/e - Ageing
    dPmature <- GrowthPm + Ageing - DeathPm
    dUnpal <- GrowthU - DeathU,
      
      ifelse(Pyoung < eps,
    # moose
    Consumption    <- ((a * 0)/(1 + a * h * 0)) * e * Moose
    Death <- lM * (Moose^2)
    
    # palatable 
    NewSeed <- s * Pmature
    GrowthPm <- rP * (Pmature) * (1 - (0 + Pmature + alphaUPm * Unpal)/kPm)
    DeathPm <- lPm * Pmature
    
    # unpalatable
    GrowthU <- rU * Unpal * (1 - (alphaPyU * 0 + alphaPmU * Pmature + Unpal)/kU)
    DeathU <- lU * Unpal

    # odes
    dMoose  <- Consumption - Death 
    dPyoung <- - Pyoung
    dPmature <- GrowthPm + Ageing - DeathPm
    dUnpal <- GrowthU - DeathU,
      
      ifelse(Pmature < eps,
    # moose
    Consumption    <- ((a * Pyoung)/(1 + a * h * Pyoung)) * e * Moose
    Death <- lM * (Moose^2)
    
    # palatable 
    GrowthPy <- rP * (Pyoung) * (1 - (Pyoung + 0 + alphaUPy * Unpal)/kPy)
    Ageing <- if(times <= 1/g) 0 else g * Pyoung  
    
    # unpalatable
    GrowthU <- rU * Unpal * (1 - (alphaPyU * Pyoung + alphaPmU * 0 + Unpal)/kU)
    DeathU <- lU * Unpal

    # odes
    dMoose  <- Consumption - Death 
    dPyoung <- GrowthPy + NewSeed - Consumption/e - Ageing
    dPmature <- -Pmature
    dUnpal <- GrowthU - DeathU,
      
      ifelse(Unpal < eps,
        # moose
    Consumption    <- ((a * Pyoung)/(1 + a * h * Pyoung)) * e * Moose
    Death <- lM * (Moose^2)
    
    # palatable 
    GrowthPy <- rP * (Pyoung) * (1 - (Pyoung + Pmature + alphaUPy * 0)/kPy)
    NewSeed <- s * Pmature
    GrowthPm <- rP * (Pmature) * (1 - (Pyoung + Pmature + alphaUPm * 0)/kPm)
    Ageing <- if(times <= 1/g) 0 else g * Pyoung  
    DeathPm <- lPm * Pmature
    
    # unpalatable

    # odes
    dMoose  <- Consumption - Death 
    dPyoung <- GrowthPy + NewSeed - Consumption/e - Ageing
    dPmature <- GrowthPm + Ageing - DeathPm
    dUnpal <- -Unpal,
      
    # moose
    Consumption    <- ((a * Pyoung)/(1 + a * h * Pyoung)) * e * Moose
    Death <- lM * (Moose^2)
    
    # palatable 
    GrowthPy <- rP * (Pyoung) * (1 - (Pyoung + Pmature + alphaUPy * Unpal)/kPy)
    NewSeed <- s * Pmature
    GrowthPm <- rP * (Pmature) * (1 - (Pyoung + Pmature + alphaUPm * Unpal)/kPm)
    Ageing <- if(times <= 1/g) 0 else g * Pyoung  
    DeathPm <- lPm * Pmature
    
    # unpalatable
    GrowthU <- rU * Unpal * (1 - (alphaPyU * Pyoung + alphaPmU * Pmature + Unpal)/kU)
    DeathU <- lU * Unpal

    # odes
    dMoose  <- Consumption - Death 
    dPyoung <- GrowthPy + NewSeed - Consumption/e - Ageing
    dPmature <- GrowthPm + Ageing - DeathPm
    dUnpal <- GrowthU - DeathU))))
    
  list(c(dMoose, dPyoung, dPmature, dUnpal))
  })
}

y03 = c(Moose = 2, Pyoung = 9, Pmature = 0, Unpal = 200)

out4 <- ode(y = y03, times = time_vec1, func = lv_event3, parms = parms)
long_out4 <- as.data.frame(out4) %>% 
  pivot_longer(cols = c(2:5))

ggplot(long_out4, aes(x = time, y = value)) +
  geom_line() +
  facet_wrap(~name, scales = "free") +
  theme_bw() 

out4
out2

steady_mat <- runsteady(y = c(Moose = 0.2, Pyoung = 100, Pmature = 80000, Unpal = 100), time= c(0, Inf), func = lv_event3, parms = parms) # mature dominating is a steady state

steady_grass <- runsteady(y = c(Moose = 2, Pyoung = 9, Pmature = 0, Unpal = 200), time= c(0, Inf), func = lv_event3, parms = parms)
```



