---
title: "Model structure"
author: "Anonymous"
date: "2024-08-27"
output: html_document
---

#libraries
```{r}
pacman::p_load(
  tidyverse,
  deSolve,
  parallel,
  pbapply,
  future.apply,
  progressr,
  rtruncnorm)
```

# model
## structure
```{r}
lv <- function(times, state, parms) {
  with(as.list(c(state, parms)), {
# moose
    Consumption    <- ((a * Pyoung)/(1 + a * h * Pyoung)) * Moose
    Death <- lM * (Moose^2)
    
    # palatable 
    GrowthPy <- rPy * Pyoung * (1 - (Pyoung + Pmature + alphaUPy * Unpal)/kPy)
    NewSeed <- s * Pmature
    DeathPy <- lPy * Pyoung
    GrowthPm <- rPm * Pmature * (1 - (Pyoung + Pmature + alphaUPm * Unpal)/kPm)
    Ageing <- g*(g^(3*(Consumption)/(Pyoung+0.01))) * Pyoung #need to add small amount to Pyoung in denominator
    DeathPm <- lPm * Pmature
    
    # unpalatable
    GrowthU <- rU * Unpal * (1 - (alphaPyU * Pyoung + alphaPmU * Pmature + Unpal)/kU)
    DeathU <- lU * Unpal

    # odes
    dMoose  <- Consumption*e - Death 
    dPyoung <- GrowthPy + NewSeed - Consumption - Ageing - DeathPy
    dPmature <- GrowthPm + Ageing - DeathPm
    dUnpal <- GrowthU - DeathU
    

    list(c(dMoose, dPyoung, dPmature, dUnpal))
  })
}
```

## extinction
```{r}
eps <- 1e-2
## event triggered if state variable <= eps
eventfun <- function(times, y, parms) {
  y[which(y<eps | y<0)] <- 0 
  return(y)
}
```

## time
```{r}
time_vec1 <- seq(from = 1, to = 1000, length.out = 1000)
```

# ranges

## initial conditions
```{r}
# make dataframe with sequence of initial conditions to sample over
# always starting from no mature and some level of unpal
# smallest values 0 for both, moose up to 6 Mg moose, and 500 Py

n_i <- 30

M_init <- seq(0, 6, length.out = n_i)
Py_init <- seq(0, 300, length.out = n_i) 
Pm_init <- rep(0, n_i)
U_init <- rep(100, n_i)

init_seq <- data.frame(Moose=rep(M_init, each = n_i), Pyoung = rep(Py_init, n_i), Pmature = rep(Pm_init,n_i), Unpal = rep(U_init,n_i))

y_0d <- split(as.matrix(init_seq), row(init_seq)) %>% 
  lapply(setNames, nm = c("Moose", "Pyoung", "Pmature", "Unpal"))

y_0d_id <- as.data.frame(t(as.data.frame(y_0d))) %>% 
  mutate(id = seq(1, length(y_0d), by = 1))
```

## parameters
```{r}
# make datafram with distribution of parameters

LVlow <-  c(0.996, #a
            0.0207933, # h
            0.01, #e
            0.2647, # lM
            0.15, #rPy
            0.1, #rPm
            0.0088, #s
            0.0005, #alphaUPy
            0.000, #alphaUPm
            400, #kPy
            20000, # kPm
            0.09, # g
            0.005, #lPm
            0.1, #lPy
            0.6,#rU
            0.001, # alphaPyU
            0.004, # alphaPmU
            300, #kU
            0.168) #lU

LVhigh <-  c(1.005, #a
            0.038735, # h
            0.03, #e
            0.3765, # lM
            0.325, #rPy
            0.2, #rPm
            0.053, #s
            0.002, #alphaUPy
            0.0002, #alphaUPm
            2000, #kPy
            80000, # kPm
            0.2, # g
            0.06, #lPm
            0.3, #lPy
            1.3 ,#rU
            0.003, # alphaPyU
            0.008, # alphaPmU
            1200, #kU
            1) #lU


param_dist <- data.frame(min = LVlow, max = LVhigh, mean = parms)
```