---
title: "predicting_space"
author: "Emmerson Wilson"
date: "2024-02-07"
output: html_document
---

```{r}
library(terra)
```


```{r}
GM_env_rast <- rast("/Users/emmersonEmmerson/Documents/Master's/C_forecasting_NL/code_for_stats/tifs for predicting/GM_env_raster.tif") # stack of enviornmental variables' rasters
TN_env_rast <- rast("/Users/emmersonEmmerson/Documents/Master's/C_forecasting_NL/code_for_stats/tifs for predicting/TN_env_raster.tif") # stack of enviornmental variables' rasters

clip_GM_rast <- rast("/Users/emmersonEmmerson/Documents/Master's/C_forecasting_NL/Environmental_datasets/clipping_files_predict/attemp 3 - rasterize roads and human use/GM_predict_binary.tif") # masking layer (cut out all human use areas, and space where values of environmental variables are outside of range sampled)
clip_TN_rast <- rast("/Users/emmersonEmmerson/Documents/Master's/C_forecasting_NL/Environmental_datasets/clipping_files_predict/attemp 3 - rasterize roads and human use/TN_predict_binary.tif")# masking layer (cut out all human use areas, and space where values of environmental variables are outside of range sampled)

clip_GM_rast[clip_GM_rast==0] <- NA
plot(clip_GM_rast) #check

clip_TN_rast[clip_TN_rast==0] <- NA
plot(clip_TN_rast) #check

GM_env_rast_masked <- crop(GM_env_rast, clip_GM_rast, mask=TRUE) # this part isn't taking out the proper cells *had to make the mask a raster
plot(GM_env_rast_masked$FHT_GM) #check

TN_env_rast_masked <- crop(TN_env_rast, clip_TN_rast, mask=TRUE)
plot(TN_env_rast_masked$EVIamp_TN) #check


# save
writeRaster(GM_env_rast_masked, filename="/Users/emmersonEmmerson/Documents/Master's/C_forecasting_NL/code_for_stats/GM_env_raster_masked.tif", overwrite=TRUE)
writeRaster(TN_env_rast_masked, filename="/Users/emmersonEmmerson/Documents/Master's/C_forecasting_NL/code_for_stats/TN_env_raster_masked.tif", overwrite=TRUE)


plot(GM_env_rast_masked$FHT_GM)
plot(TN_env_rast_masked$FHT_TN)
```

